crossm/crossm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import InstructionView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('companies/', include('companies.urls')),
    path('offers/', include('offers.urls')),
    path('', InstructionView.as_view(), name='instruction'),
]

handler404 = "crossm.views.page_not_found_view"
handler403 = "crossm.views.handler403"

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


crossm/offers/urls.py
from django.urls import path, include
from .views import CreateOfferView, DeleteOfferView, UpdateOfferView, \
    OfferImageDeleteView, MyOffersPageView, SendImagesView, CatalogPageView

app_name = 'offers'
urlpatterns = [
    path('create/<int:pk>', CreateOfferView.as_view(), name='create-offer'),
    path('delete/', DeleteOfferView.as_view(), name='delete-offer'),
    path('update/<int:pk>', UpdateOfferView.as_view(), name='update-offer'),
    path('delete/image/', OfferImageDeleteView.as_view(), name='delete-image'),
    path('myoffers/', MyOffersPageView.as_view(), name='my-offers'),
    path('getimages/', SendImagesView.as_view(), name='get-images'),
    path('catalog/', CatalogPageView.as_view(), name='catalog'),



]

crossm/users/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from .views import RegisterView, LoginView, SetProfileInfo, ProfileView, \
    ProfileUpdateView, ProfilePhotoUpload, DeletePhotoView, WhatisCMView, CheckProfilePhoto, GetAiHelp, \
    CrossMHelp, TechnicalHelp, UserEnrollment, CheckRefCodeView

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('register/<str:ref_code>', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('setprofileinfo/', SetProfileInfo.as_view(), name='set-profile-info'),
    path('', include('django.contrib.auth.urls')),
    path('profile/<int:pk>', ProfileView.as_view(), name='view-profile'),
    path('profile/update/', ProfileUpdateView.as_view(), name='update-profile'),
    path('profile/photoupload/', ProfilePhotoUpload.as_view(), name='upload-photo'),
    path('profile/photodelete/', DeletePhotoView.as_view(), name='delete-photo'),
    path('whatis', WhatisCMView.as_view(), name='what-is-cm'),
    path('checkphoto', CheckProfilePhoto.as_view(), name='check-photo'),
    path('getaihelp', GetAiHelp.as_view(), name='get-ai-help'),
    path('techhelp', TechnicalHelp.as_view(), name='tech-help'),
    path('crossmhelp', CrossMHelp.as_view(), name='crossm-help'),
    path('enrollment', UserEnrollment.as_view(), name='user-enrollment'),
    path('checkrefcode', CheckRefCodeView.as_view(), name='check-ref-code'),
]

crossm/crossm/views.py
from django.http import JsonResponse, HttpResponseForbidden
from django.shortcuts import render
from django.views.generic import TemplateView
from django_ratelimit.exceptions import Ratelimited
from users.views import get_profile_ph


def page_not_found_view(request, exception):
    return render(request, '404.html', status=404)


def handler403(request, exception=None):
    if isinstance(exception, Ratelimited):
        return JsonResponse({'text': 'banned', 'message': 'Вы превысили допустимый лимит запросов'})
    return HttpResponseForbidden('Forbidden')


class InstructionView(TemplateView):
    template_name = 'instruction.html'

    def get_context_data(self, **kwargs):
        return {'profile_ph': get_profile_ph(self.request)}

crossm/crossm/templates/base.html

        <header class="header">
            <div class="header-container">
                    <nav class="nav">
                        <div class="nav-logo nav-logo-instruction">
                            <a href="#" class="nav-log__title">КроссМ</a>
							<a href="{% url 'instruction' %}" class="a-instruction">Инструкция по сайту</a>
                        </div>
                        <div class="menu">
                            <a id="CATALOG" href="{% url 'offers:catalog' %}" class="nav-menu__title">Каталог</a>
                            <a id="KM" href="{% url 'what-is-cm' %}" class="nav-menu__title">Что такое КМ?</a>
                            <a id="OFFERS" href="{% url 'offers:my-offers' %}" class="nav-menu__title">Мои предложения</a>
                            {% if user.is_authenticated %}
                            <div onclick="window.location.href = '{% url 'view-profile' request.user.id %}'" class="nav-menu__user">
                                {% if profile_ph %}
                                <img id="header-image" class="nav-menu__user__img" src="{{profile_ph}}">
                                {% else %}
                                <img id="header-image" class="nav-menu__user__img" src="/media/images/no_company_logo.png">
                            {% endif %}
                            </div>
                            {% endif %}
                        </div>
                    </nav>
            </div>
        </header>

crossm/crossm/templates/favicon.html
{% load static %}
<link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.ico' %}"/>

crossm/crossm/templates/footer-mobile.html
<div class="footer-margin"></div>
        <div class="footer-bottom">
            <div class="footer-bottom__content">
                <a href="{% url 'instruction' %}" class="footer-logo-bottom">
                    <p class="">КроссМ</p>
                    <p class="p-mobile-logo p-mobile-instruction">инструкция</p>

                </a>
                <a href="{% url 'offers:catalog' %}" class="footer-item">
                    <img src="../../../static/images/catalog-icon.svg" class="footer-item__img">
                    <p id="CATALOG_MOBILE" class="footer-item__text">каталог</p>
                </a>
                <a href="{% url 'what-is-cm' %}" class="footer-item">
                    <img src="../../../static/images/what-is-icon.svg" class="footer-item__img">
                    <p id="KM_MOBILE" class="footer-item__text">что такое<br>км?</p>
                </a>
                <a href="{% url 'offers:my-offers' %}" class="footer-item">
                    <img src="../../../static/images/my-offers-icon.svg" class="footer-item__img">
                    <p id="OFFERS_MOBILE" class="footer-item__text">предло<br>жения</p>
                </a>
				{% if request.user.is_authenticated %}
				{% if profile_ph %}
                <a href="{% url 'view-profile' request.user.id %}" class="footer-item">
                    <img style="margin-bottom: 2px; margin-top: -2px;   border-radius: 50%;" src="{{profile_ph}}" class="footer-item__img">

                    <p class="footer-item__text">профиль</p>
                </a>
				{% else %}
				<a href="{% url 'view-profile' request.user.id %}" class="footer-item">
                    <img style="margin-bottom: 2px; margin-top: -2px;   border-radius: 50%;" src="/media/images/no_company_logo.png" class="footer-item__img">

                    <p class="footer-item__text">профиль</p>
                </a>
				{% endif %}
				{% else %}
				<a href="{% url 'login' %}" class="footer-item">
                    <img style="margin-bottom: 2px; margin-top: -2px;   border-radius: 50%;" src="/media/images/no_company_logo.png" class="footer-item__img mobile-footer-logo">
                    <p class="footer-item__text">вход</p>
                </a>
				{% endif %}
            </div>
        </div>

        

crossm/crossm/templates/footer.html
 <footer class="footer">
            <div class="footer-container">
                <hr class="hr-solid mg-bottom-48px">
                <div class="footer-content">
                    <div class="footer-logo">
                        <a href="#" class="nav-log__title">КроссМ</a>
                    </div>
                    <div class="footer-arrow">
                        <div class="test-arrow">
                            <hr class="hr-solid-arrow">
                        </div>

                    </div>
                    <div class="footer-nav">
                    <div class="footer-top-titles">
                        <span onclick="window.location.href = '{% url 'offers:catalog' %}'" class="nav-menu__title">Каталог</span>
                        <span onclick="window.location.href = '{% url 'what-is-cm' %}'" class="nav-menu__title">Что&nbspтакое&nbspКМ?</span>
                        <span onclick="window.location.href = '{% url 'offers:my-offers' %}'" class="nav-menu__title">Мои&nbspпредложения</span>
                    </div>

                    </div>
                </div>
                <p class="nav-menu__title-policy policy">Политика конфиденциальности</p>
                <div class="footer-contacts">
                    <p class="prava">Все права защищены @2023</p>
                    <p class="developer">Сайт разработан командой Старрук инк :)</p>
                </div>
            </div>
        </footer>

crossm/crossm/templates/instruction.html
{% load static %}

<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;900&display=swap"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
	  {% include "favicon.html" %}
    <title>PMarket | Инструкция</title>
  </head>
  <body>

  {% include "base.html" %}

    <main class="main">
      <div class="container-padding">
        <div class="container-main">
            <div class="greeting">
                <h2 class="hello">Добро пожаловать на сайт КроссМ!</h2>
                <div class="hello-subtitle">
                    <span>Если Вы на сайте НЕ первый раз, то Вы можете </span>
                    <a href="{% url 'login' %}" class="login">войти в свой аккаунт здесь</a>
                </div>
            </div>
            <div class="greeting">
                <h2 class="hello">Для чего этот сайт?</h2>
                <div class="hello-subtitle">
                  <span>КроссМ — это платформа для поиска партнеров по кросс-маркетингу. Что такое кросс-маркетинг </span>
                  <a href="{% url 'what-is-cm' %}" class="login">можно узнать тут</a>
              </div>
            </div>
            <div class="container-instruction"> 
                <h2 style="text-align: center; margin-bottom: 20px;" class="hello">Как пользоваться сайтом?</h2>
                <section class="section-instruction">
                    <p class="instruction-subtitle">Вариант 1 — найти предложения для увеличения своего среднего чека</p>
                    <p class="list-title">1.  Перейти</p>
                    <p class="list-subtitle">Перейти во вкладку каталог в верхнем меню</p>
                    <image class="instruction-img" src="../../../static/images/instrustion-image-1.png"></image>
                    <p class="list-title">2. Отфильтровать</p>
                    <p style="max-width: 540px" class="list-subtitle">Отфильтровать предложения компаний по нужным критериям (ниша/цена купона/количество купонов и т.д.)</p>
                    <image class="instruction-img" src="../../../static/images/instrustion-image-2.png"></image>
                    <p class="list-title">3. Изучить</p>
                    <p style="max-width: 540px" class="list-subtitle">Если Вы нашли интересную компанию в каталоге, Вы можете нажать на нее, чтобы посмотреть полный профиль этой компании</p>
                    <image class="instruction-img" src="../../../static/images/instrustion-image-3.png"></image>
                    <p class="list-title">4. Связаться</p>
                    <p style="max-width: 540px" class="list-subtitle">На каждой карточке в каталоге содержится информация о представителе компании и его контактах. Вы можете связаться с представителем и договориться о дальнейшем сотрудничестве.</p>
                    <image class="instruction-img" src="../../../static/images/instrustion-image-4.png"></image>
                    <p style="color: rgba(0, 0, 0, 0.5);" class="list-title">5. Оставить отзыв — в разработке</p>
                    <p style="max-width: 650px; color: rgba(0, 0, 0, 0.5);" class="list-subtitle">Если все получилось, и Вы договорились о выгодном сотрудничестве — напишите отзыв о Вашем новом партнере у него в профиле компании. Если компания оказалась недобросовестной — обязательно напишите отзыв у нее в профиле. Это важно для того, чтобы другие предприниматели не теряли время.</p>
                </section>
                <section class="section-instruction">
                  <p class="instruction-subtitle">Вариант 2 — разместить предложение на продукт или услугу, чтобы получить лидов</p>
                  <p class="list-title">1.  Зарегистрироваться</p>
                  <div style="margin-bottom: 12px; text-align: left;" class="hello-subtitle">
                    <span class="list-subtitle">Зарегистрироваться </span>
                    <a href="{% url 'register' %}" class="login list-subtitle">можно по этой ссылке</a>
                  </div>
                  <image class="instruction-img" src="../../../static/images/instrustion-image-5.png"></image>
                  <p class="list-title">2. Заполнить информацию</p>
                  <div style="margin-bottom: 8px; text-align: left; max-width: 700px" class="hello-subtitle">
                    <span class="list-subtitle">Заполнить необходимую информацию.</span>
                    <span class="list-subtitle black-underline">Без этого пункта невозможно продолжить</span>
                  </div>                  <image class="instruction-img" src="../../../static/images/instrustion-image-6.png"></image>
                  <p class="list-title">3. Создать и оформить компанию</p>
                  <p style="max-width: 540px" class="list-subtitle">После заполнения формы Вы попадёте на страницу создания компании</p>
                  <image class="instruction-img" src="../../../static/images/instrustion-image-7.png"></image>
                  <p class="list-title">4. Создать предложение</p>
                  <p style="max-width: 540px" class="list-subtitle">После создания компании Вы попадёте на страницу создания предложения от лица только что созданной компании</p>
                  <image class="instruction-img" src="../../../static/images/instrustion-image-8.png"></image>
                  <p class="list-title">5. Ожидать</p>
                  <p style="max-width: 650px;" class="list-subtitle"><span class="bottom-underline">Теперь Ваше предложение видно всем пользователям платформы.</span> Вы можете увеличить количество откликов, если разрешите отображение номера телефона в профиле. <span class="bottom-underline">Пользователям виден Ваш адрес электронной почты, так что не забывайте ее проверять</span></p>
              </section>
              <section class="section-instruction">
                <p style="max-width: 580px;" class="instruction-subtitle">— Рекомендации для более эффективного использования платформы</p>
                <p class="list-title">1.  Добавить логотип компании</p>
                <p class="list-subtitle">Добавить логотип компании можно на странице компании</p>
                <image style="margin-bottom:8px;" class="instruction-img" src="../../../static/images/instrustion-image-9.png"></image>
                <image class="instruction-img" src="../../../static/images/instrustion-image-10.png"></image>
                <p class="list-title">2.  Поставить свое фото в профиль</p>
                <p style="max-width: 540px; margin-bottom: 24px;" class="list-subtitle">Поставить свое фото можно в профиле по такому же принципу, как и фото компании (пункт 1)</p>
                <p class="list-title">3.  Заполнить комментарий в профиле</p>
                <p style="max-width: 540px" class="list-subtitle">Если Вы не написали комментарий при регистрации, его можно написать в любой момент во вкладке “Редактирование профиля”</p>
                <image style="margin-bottom:8px;" class="instruction-img" src="../../../static/images/instrustion-image-11.png"></image>
                <image class="instruction-img" src="../../../static/images/instrustion-image-12.png"></image>
                <p class="list-title">4.  Заполнить комментарий в профиле компании</p>
                <p style="max-width: 630px; max-width: 680px;" class="list-subtitle">Написать комментарий в профиле компании можно по такому же принципу, как и комментарий в личный профиль (инструкиция в 3 пункте)</p>
            </section>
            </div>
        </div>
      </div>
    </main>
    {% include "footer-mobile.html" %}

    {% include "footer.html" %}
    <!-- <div class="bottom-margin"></div> -->
  </body>
</html>