crossm/crossm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import InstructionView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('companies/', include('companies.urls')),
    path('offers/', include('offers.urls')),
    path('', InstructionView.as_view(), name='instruction'),
]

handler404 = "crossm.views.page_not_found_view"
handler403 = "crossm.views.handler403"

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


crossm/offers/urls.py
from django.urls import path, include
from .views import CreateOfferView, DeleteOfferView, UpdateOfferView, \
    OfferImageDeleteView, MyOffersPageView, SendImagesView, CatalogPageView

app_name = 'offers'
urlpatterns = [
    path('create/<int:pk>', CreateOfferView.as_view(), name='create-offer'),
    path('delete/', DeleteOfferView.as_view(), name='delete-offer'),
    path('update/<int:pk>', UpdateOfferView.as_view(), name='update-offer'),
    path('delete/image/', OfferImageDeleteView.as_view(), name='delete-image'),
    path('myoffers/', MyOffersPageView.as_view(), name='my-offers'),
    path('getimages/', SendImagesView.as_view(), name='get-images'),
    path('catalog/', CatalogPageView.as_view(), name='catalog'),



]

crossm/users/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from .views import RegisterView, LoginView, SetProfileInfo, ProfileView, \
    ProfileUpdateView, ProfilePhotoUpload, DeletePhotoView, WhatisCMView, CheckProfilePhoto, GetAiHelp, \
    CrossMHelp, TechnicalHelp, UserEnrollment, CheckRefCodeView

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('register/<str:ref_code>', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('setprofileinfo/', SetProfileInfo.as_view(), name='set-profile-info'),
    path('', include('django.contrib.auth.urls')),
    path('profile/<int:pk>', ProfileView.as_view(), name='view-profile'),
    path('profile/update/', ProfileUpdateView.as_view(), name='update-profile'),
    path('profile/photoupload/', ProfilePhotoUpload.as_view(), name='upload-photo'),
    path('profile/photodelete/', DeletePhotoView.as_view(), name='delete-photo'),
    path('whatis', WhatisCMView.as_view(), name='what-is-cm'),
    path('checkphoto', CheckProfilePhoto.as_view(), name='check-photo'),
    path('getaihelp', GetAiHelp.as_view(), name='get-ai-help'),
    path('techhelp', TechnicalHelp.as_view(), name='tech-help'),
    path('crossmhelp', CrossMHelp.as_view(), name='crossm-help'),
    path('enrollment', UserEnrollment.as_view(), name='user-enrollment'),
    path('checkrefcode', CheckRefCodeView.as_view(), name='check-ref-code'),
]

crossm/offers/models.py
from django.db import models
from companies.models import Companies
from PIL import Image


class Offers(models.Model):
    company = models.ForeignKey(Companies, on_delete=models.CASCADE)
    type = models.CharField(max_length=30)
    
    coupon_price = models.DecimalField(decimal_places=2, max_digits=9)
    currency = models.CharField(max_length=6)
    
    retail_price = models.DecimalField(decimal_places=2, max_digits=10)
    title = models.CharField(max_length=80)
    amount_min = models.IntegerField(blank=False, null=True)
    amount_max = models.IntegerField(blank=False, null=True)
    
    has_photo = models.BooleanField(null=True)
    
    def natural_key(self):
        return (self.title,) + self.company.natural_key() + self.company.owner.natural_key()
    
    natural_key.dependencies = ['companies.companies', 'users.user']


class OffersImages(models.Model):
    offer = models.ForeignKey(Offers, on_delete=models.CASCADE)
    image = models.FileField(upload_to='images/')
    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        instance = self
        image = Image.open(instance.image.path)
        image.save(instance.image.path, quality=60, optimize=True)
        return instance

crossm/offers/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import Offers
from django.db.models.fields import BLANK_CHOICE_DASH


def get_currency_choices():
    return [
        ('BYN', 'BYN'),
        ('RUB', 'RUB')
    ]


TYPE_CHOICES = [
    ('Товар', 'Товар'),
    ('Услуга', 'Услуга')
]


class CreateOfferForm(forms.ModelForm):
    image = forms.ImageField(required=False, widget=forms.ClearableFileInput(attrs={
        'multiple': True,
        'class': 'file-input',
        'id': 'choose-file-container',
        'accept': 'image/*'
    }))

    class Meta:
        model = Offers
        fields = ['coupon_price', 'currency', 'retail_price', 'title',
                  'amount_min', 'amount_max', 'type']
        widgets = {
            'title': forms.TextInput(attrs={
                'class': 'input input-620px',
                'placeholder': 'Введите название услуги'
            }),
            'coupon_price': forms.NumberInput(attrs={
                'class': 'input input-300px',
                'placeholder': 'Введите цену'
            }),
            'currency': forms.Select(choices=BLANK_CHOICE_DASH + get_currency_choices(), attrs={
                'class': 'js-choice',
            }),
            'retail_price': forms.NumberInput(attrs={
                'class': 'input input-620px',
                'placeholder': 'Введите розничную цену'
            }),
            'amount_min': forms.NumberInput(attrs={
                'class': 'input input-300px',
                'placeholder': 'От',
            }),
            'amount_max': forms.NumberInput(attrs={
                'class': 'input input-300px',
                'placeholder': 'До',

            }),
            'type': forms.Select(choices=BLANK_CHOICE_DASH + TYPE_CHOICES, attrs={
                'class': 'js-choice',
            })
        }

    def clean_amount_max(self):
        if self.cleaned_data['amount_min'] > self.cleaned_data['amount_max']:
            raise forms.ValidationError('Введите корректные значения для полей "Количество купонов"')
        return self.cleaned_data['amount_max']


crossm/offers/views.py
from django.core.paginator import Paginator, EmptyPage
from django.core.serializers import serialize
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import CreateOfferForm
from companies.models import Companies, Countries
from .models import OffersImages, Offers
from django.views.generic import DeleteView
from users.models import User
from django.http import Http404, JsonResponse, HttpResponse, HttpResponseRedirect
from funcy import omit
from django.dispatch import receiver
import os
from django.db.models.signals import post_delete, pre_save
from users.views import get_profile_ph
from users.models import Profile
import json
from users.mixins import AccessForCompletesOnlyMixin, AccessForMembersOnlyMixin
# from users.views import is_allowed


class CreateOfferView(AccessForMembersOnlyMixin, View):
    template_name = 'offers/create_offer.html'

    def get(self, request, **kwargs):

        # try:
        #     is_allowed(request)
        # except PermissionError:
        #     return redirect('set-profile-info')

        context = {
            'form': CreateOfferForm(),
            'profile_ph': get_profile_ph(request),
        }
        return render(request, self.template_name, context)

    def post(self, request, **kwargs):

        # try:
        #     is_allowed(request)
        # except PermissionError:
        #     return redirect('set-profile-info')

        form = CreateOfferForm(request.POST, request.FILES)
        company_id = kwargs['pk']
        images = request.FILES.getlist('image')

        company = Companies.objects.filter(id=company_id, owner=request.user).first()
        if not company:
            raise Http404

        if form.is_valid():

            obj = form.save(commit=False)
            obj.company = company
            obj.save()
            for i in images:
                OffersImages(offer=obj, image=i).save()

            nexty = request.POST.get('next')
            if nexty:
                try:
                    return HttpResponseRedirect(nexty)
                except:
                    raise Http404
            else:
                return redirect('offers:my-offers')

        context = {
            'form': form,
            'profile_ph': get_profile_ph(request),
        }
        return render(request, self.template_name, context)


class DeleteOfferView(AccessForMembersOnlyMixin, View):
    def post(self, request, **kwargs):
        obj = get_object_or_404(Offers, id=request.POST.get('id'))

        if obj.company.owner != self.request.user:
            raise Http404

        obj.delete()
        data = {'deleted': True, 'success': True}
        return JsonResponse(data)


class UpdateOfferView(AccessForMembersOnlyMixin, View):
    template_name = 'offers/update_offer.html'

    def get(self, request, **kwargs):

        # try:
        #     is_allowed(request)
        # except PermissionError:
        #     return redirect('set-profile-info')

        obj = get_object_or_404(Offers, id=kwargs['pk'])

        if obj.company.owner != request.user:
            raise Http404

        context = {
            'form': CreateOfferForm(initial={
                'type': obj.type,
                'coupon_price': obj.coupon_price,
                'currency': obj.currency,
                'retail_price': obj.retail_price,
                'title': obj.title,
                'amount_min': obj.amount_min,
                'amount_max': obj.amount_max
            }),
            'images': OffersImages.objects.filter(offer=obj).all(),
            'profile_ph': get_profile_ph(request),
        }
        return render(request, self.template_name, context)

    def post(self, request, **kwargs):

        # try:
        #     is_allowed(request)
        # except PermissionError:
        #     return redirect('set-profile-info')

        instance = get_object_or_404(Offers, id=kwargs['pk'])

        if instance.company.owner != request.user:
            raise Http404

        form = CreateOfferForm(request.POST, request.FILES, instance=instance)
        images = request.FILES.getlist('image')

        if form.is_valid():
            obj = form.save()
            for i in images:
                OffersImages(offer=obj, image=i).save()

            nexty = request.POST.get('next')
            if nexty:
                try:
                    return HttpResponseRedirect(nexty)
                except:
                    raise Http404
            else:
                return redirect('offers:my-offers')

        context = {
            'form': form,
            'profile_ph': get_profile_ph(request),
        }
        return render(request, self.template_name, context)


class OfferImageDeleteView(AccessForMembersOnlyMixin, View):
    def get(self, request, **kwargs):
        post = get_object_or_404(OffersImages, id=request.GET.get('id'))
        if post.offer.company.owner == request.user:
            post.delete()
            return JsonResponse({'success': True})
        else:
            return Http404


@receiver(post_delete, sender=OffersImages)
def post_save_image(sender, instance, *args, **kwargs):
    """ Clean Old Image file """
    try:
        instance.image.delete(save=False)
    except:
        pass


class MyOffersPageView(AccessForMembersOnlyMixin, View):
    template_name = 'offers/my_offers.html'

    def get(self, request, **kwargs):

        # try:
        #     is_allowed(request)
        # except PermissionError:
        #     return redirect('set-profile-info')

        objects = Companies.objects.filter(owner=request.user).prefetch_related('offers_set',
                                                                                'owner__profile_set').all()
        context = {
            'objects': objects,
            'profile_ph': get_profile_ph(request),
        }
        return render(request, self.template_name, context)


class SendImagesView(AccessForMembersOnlyMixin, View):
    def get(self, request, **kwargs):
        images = OffersImages.objects.filter(offer=request.GET.get('id')).all()
        res = []
        for image in images:
            res.append(image.image.url)
        return JsonResponse({'images': res})


class CatalogPageView(View):
    catalog_template = 'offers/catalog.html'
    catalog_template_hidden = 'offers/catalog-hidden.html'
    
    def get_template(self):
        if self.request.user.is_authenticated:
            if self.request.user.role >= User.INVITED:
                return self.catalog_template
        return self.catalog_template_hidden
    
    def get(self, request, **kwargs):
        offers = Offers.objects.prefetch_related('offersimages_set', 'company__owner__profile_set').order_by(
            '-id').all()
        currencies = Offers.objects.values('currency').distinct()
        niches = Companies.objects.values('niche').distinct()

        # niche = request.GET.get('niche')
        # if niche:
        #     initial_offers = initial_offers.filter(company__niche=niche)
        #
        # amount_min = request.GET.get('amount_min')
        # amount_max = request.GET.get('amount_max')
        # if amount_min and amount_max:
        #     initial_offers = initial_offers.filter(amount_min__lte=amount_max, amount_max__gte=amount_min)
        # elif amount_min:
        #     initial_offers = initial_offers.filter(amount_max__gte=amount_min)
        # elif amount_max:
        #     initial_offers = initial_offers.filter(amount_min__lte=amount_max)
        #
        # currency = request.GET.get('currency')
        # if currency:
        #     initial_offers = initial_offers.filter(currency=currency)
        #
        # retail_price_min = request.GET.get('retail_price_min')
        # retail_price_max = request.GET.get('retail_price_max')
        # if retail_price_min and retail_price_max:
        #     initial_offers = initial_offers.filter(retail_price__gte=retail_price_min,
        #                                            retail_price__lte=retail_price_max)
        # elif retail_price_min:
        #     initial_offers = initial_offers.filter(retail_price__gte=retail_price_min)
        # elif retail_price_max:
        #     initial_offers = initial_offers.filter(retail_price__lte=retail_price_max)
        #
        # coupon_price_min = request.GET.get('coupon_price_min')
        # coupon_price_max = request.GET.get('retail_price_max')
        # if coupon_price_min and coupon_price_max:
        #     initial_offers = initial_offers.filter(retail_price__gte=coupon_price_min,
        #                                            retail_price__lte=coupon_price_max)
        # elif coupon_price_min:
        #     initial_offers = initial_offers.filter(retail_price__gte=coupon_price_min)
        # elif coupon_price_max:
        #     initial_offers = initial_offers.filter(retail_price__lte=coupon_price_max)
        #
        # country = request.GET.get('country')
        # if country:
        #     initial_offers = initial_offers.filter(company__country_of_res=country)
        #
        # phone_num_show = request.GET.get('phone_num_show')
        # #phone_num_show = 1
        # if phone_num_show:
        #     suitable_users = Profile.objects.filter(phone_num_show=True).values_list('user_id', flat=True)
        #     initial_offers = initial_offers.filter(company__owner__id__in=suitable_users)
        #
        # print(initial_offers)
        #
        # p = Paginator(initial_offers, 2)
        #
        # page = request.GET.get('page')
        #
        # try:
        #     res = p.page(page)
        # except EmptyPage:

crossm/offers/templates/offers/update_offer.html
<!--<form method="post" enctype="multipart/form-data">-->
<!--    {% csrf_token%}-->
<!--{{form}}-->
<!--<button class="last-button-add" type="submit" id="upload">-->

<!--  <p class="button-p">Сохранить</p>-->

<!--</button>-->
<!--</form>-->
<!--{% if form.errors %}-->
<!--{{form.errors.error}}-->
<!--{% endif %}-->

<!DOCTYPE html>
{% load static %} {% load widget_tweaks %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;900&display=swap"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/choices.js@9.0.1/public/assets/styles/choices.min.css"
    />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
	  {% include "favicon.html" %}
    <title>Редактирование предложения</title>
  </head>
  <body>

    <div class="Test"></div>

    {% include "base.html" %} {% block content %}

    <main>
      <div class="container-padding">
        <div class="container">
          <h2 class="main-title">Создание предложения</h2>
          <hr class="hr-solid" />
          <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="inputs">
              <div class="inputs-part inputs-part__double">
                <h3 class="inputs-part__title">Услуга</h3>
                <div class="inputs-part__div">
                  {{form.title|attr:"maxlength:80"}}
                </div>
                <p class="input__comment">
                  Напишите название услуги. <br />Максимальное количество
                  символов —
                </p>
              </div>

              <div class="inputs-part inputs-part__double">
                <h3 class="inputs-part__title">Количество купонов</h3>
                <div class="inputs-part__double-flex">
                  <div class="inputs-part inputs-part__double">
                    <div class="inputs-part__div">
                      {{form.amount_min|attr:"maxlength:4"}}
                    </div>

                    <!-- <p class="input__comment">Напишите желаемое количество купонов для реализации.</p> -->
                  </div>

                  <div class="inputs-part__300px">
                    <div class="inputs-part__div">
                      {{form.amount_max|attr:"maxlength:4"}}
                    </div>

                    <!-- <p class="input__comment">Введите валюту</p> -->
                  </div>
                </div>
                <p class="input__comment">Напишите желаемое количество купонов для реализации. Точное число или, например ОТ ... или ОТ ... ДО ...</p>

              </div>

            </div>
            <div class="line">
              <hr class="line__dashed line__dashed-620" />
              <hr class="line__dashed line__dashed-620" />
            </div>

            <div class="inputs">
              <div class="inputs-part inputs-part__double">
                <h3 class="inputs-part__title">Розничная цена</h3>
                <div class="inputs-part__div">
                  {{form.retail_price|attr:"maxlength:10"}}
                </div>
                <p class="input__comment">
                  Здесь укажите цену услуги при розничной продаже
                </p>
              </div>

              <div class="inputs-part inputs-part__double">
                <div class="inputs-part__double-flex">
                  <div class="inputs-part inputs-part__double">
                    <h3 class="inputs-part__title">Цена купона</h3>
                    <div class="inputs-part__div">
                      {{form.coupon_price|attr:"maxlength:10"}}
                    </div>
                    <p class="input__comment">Здесь укажите цену 1 купона</p>
                  </div>

                  <div class="inputs-part__300px">
                    <h3 class="inputs-part__title">Валюта</h3>
                    <div class="inputs-part__div">{{form.currency}}</div>
                    <div class="bottom-16px"></div>
                    <p class="input__comment">Введите валюту</p>
                  </div>
                </div>
              </div>
            </div>

            <div class="line">
              <hr class="line__dashed line__dashed-620" />
              <div class="left-hr">
                <hr class="line__dashed line__dashed-300" />
                <hr class="line__dashed line__dashed-300" />
              </div>
            </div>

            <div class="inputs">
              <div class="inputs-part inputs-part__double">
                <h3 class="inputs-part__title">Фото купонов</h3>
                <div class="inputs-part__div">
                  <div class="file-form">
                    <div class="choose-file-container input-620px-single">
                      <label class="choose-file-button" id="test">
                        {{form.image}}
                        <span class="button-file">Выбрать файлы</span>
                      </label>
                    </div>
                  </div>
                </div>
                <div class="bottom-16px"></div>
                <p class="input__comment">
                  Пишитие, пожалуйста с 9 до 20 в вайбер на номер телфона
                </p>
              </div>

              <div class="inputs-part inputs-part__double">
                <h3 class="inputs-part__title">Тип предложения</h3>
                <div class="inputs-part__div">{{form.type}}</div>
                <div class="bottom-16px"></div>
                <p class="input__comment">
                  Выберите нишу Вашей компании. Если в списке нет того, что Вам
                  <br class="br-to-hide" />нужно, выберите наиболее подходящую
                </p>
              </div>
            </div>
            <div class="line">
              <hr class="line__dashed line__dashed-620" />
              <hr class="line__dashed line__dashed-620" />
            </div>

            <div class="button-submit mobile-not-flex">
              <button class="button button-240px" type="submit" name="next" value="{{ request.GET.next }}">
                <p class="button-p">Сохранить</p>
              </button>

				      <a href="{% url 'tech-help' %}" class="a-account support-mobile a-inline-mobile">
                Написать в техподдержку
            </a>
            </div>
          </form>

          {% if form.non_field_errors or form.title.errors or form.amount.errors or form.retail_price.errors or form.coupon_price.errors or form.type.errors or form.image.errors or form.currency.errors %}
          <div class="error">
            {% if form.non_field_errors %} {% for error in form.non_field_errors %}
            <div class="error-item">{{error}}</div>
            {% endfor %} {% endif %} {% if form.title.errors %} {% for error in form.title.errors %}
            <div class="error-item">{{error}}</div>
            {% endfor %} {% endif %} {% if form.amount.errors %} {% for error in form.amount.errors %}
            <div class="error-item">{{error}}</div>
            {% endfor %} {% endif %} {% if form.coupon_price.errors %} {% for error in form.coupon_price.errors %}
            <div class="error-item">{{error}}</div>
            {% endfor %} {% endif %} {% if form.retail_price.errors %} {% for error in form.retail_price.errors %}
            <div class="error-item">{{error}}</div>
            {% endfor %} {% endif %} {% if form.currency.errors %} {% for error in form.currency.errors %}
            <div class="error-item">{{error}}</div>
            {% endfor %} {% endif %} {% if form.type.errors %} {% for error in form.type.errors %}
            <div class="error-item">{{error}}</div>
            {% endfor %} {% endif %} {% if form.image.errors %} {% for error in form.image.errors %}
            <div class="error-item">{{error}}</div>
            {% endfor %} {% endif %}
          </div>
          {% endif %}
        </div>
      </div>
    </main>
    <!-- {% include "footer-mobile.html" %} -->


    <!--                        <p>Старые фото</p>-->
    <!--                    {% for i in images %}-->
    <!--                    <img id="image-{{i.id}}" src="{{i.image.url}}" width="100px" height="100px">-->
    <!--                    <div id="button-{{i.id}}" class="button-278px">-->

    <!--                                    <a onclick="deleteUser({{i.id}})" class="button-p">Удалить фото</a>-->

    <!--                            </div>-->
    <!--                    {% endfor %}-->

    <!--                    <output><p>Новые фото</p></output>-->

    <section style="margin-top: 24px">
      <div class="container-padding">
        <div class="container">
          <h3 class="mg-bottom-24px inputs-part__title attachments-mobile">
            Вложения
          </h3>
          {% if images %}
          <div class="images-delete-container">
            {% for i in images %}
            <div class="image-container">
              <img
                id="image-{{i.id}}"
                src="{{i.image.url}}"
                alt=""
                class="small-image"
              />
              <a
                id="img-button{{i.id}}"
                onclick="deleteUser({{i.id}})"
                class="delete-image"
                >Удалить фото</a
              >
            </div>
            {% endfor %}
            <div class="images-delete-container" id="new-img"></div>
          </div>

          {% else %}

          <p style="position: static; margin-top: -4px" class="p-no-reviews">
            Сохраненных вложений пока нет
          </p>
          <div class="images-delete-container" id="new-img"></div>
          {% endif %}
        </div>
      </div>
    </section>
    {% include "footer-mobile.html" %}


    {% include "footer.html" %}
    <script src="{% static 'js/file-animation.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/choices.js@9.0.1/public/assets/scripts/choices.min.js"></script>
    <script src="{% static 'js/main.js' %}"></script>

    <script>
      function deleteUser(id)

{
          $.ajax({
            url: '{% url "offers:delete-image" %}',
            data: {
              id: id,
            },
            dataType: "json",
            success: function (data) {
              $("#image-" + id).remove();
              $("#img-button-" + id).remove();
            },
            type: "GET",
          });

}


      const output = document.querySelector("#new-img");
      const input = document.getElementById("choose-file-container");
      let imagesArray = [];

      function displayImages() {
        let images = "";
        imagesArray.forEach((image, index) => {
          images += `<div class="image-container">
                <img src="${URL.createObjectURL(
                  image
                )}" alt="" class="small-image">
                <a id = '${index}' class="delete-image" onclick="deleteImage(${index}, id)">Удалить фото</a>
              </div>`;
        });
        output.innerHTML = images;
        document.querySelector('.p-no-reviews').style.display = 'none';
      }

      function deleteImage(index, id) {
        
        document.getElementById(`${id}`).parentNode.style.display = 'none'
        document.querySelector('.button-file').addEventListener('click', () => {
          if (document.getElementById('new-img')) {
            document.getElementById('new-img').display = 'none'
          }
        })


        const dt = new DataTransfer();
        const input = document.getElementById("choose-file-container");
        const { files } = input;

        for (let i = 0; i < files.length; i++) {
          const file = files[i];
          if (index !== i) dt.items.add(file); // here you exclude the file. thus removing it.
        }

        input.files = dt.files; // Assign the updates list

        if (imagesArray.length -1 === 0) {
            // document.querySelector('#test').style.float = 'left';
            document.querySelector('.p-no-reviews').style.display = 'block';
            document.querySelector('.button-file').innerText = 'Выбрать файлы';
            // document.querySelector('.choose-file-button').style.backgroundColor = '#000000';
        }
        
        imagesArray.splice(index, 1);
        // displayImages();
      }

      input.addEventListener("change", () => {
        const files = input.files;
        for (let i = 0; i < files.length; i++) {
          imagesArray.push(files[i]);
        }
        displayImages();
      });

    
document.querySelector('.choose-file-button').addEventListener('click', () => {
          if (document.getElementById('new-img')) {
            document.getElementById('new-img').innerHTML = ''
            imagesArray = [];
            images = "";
          }
        })


    </script>
  </body>
  {% endblock %}
</html>